# Generated by Django 3.2.2 on 2021-05-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_useremailverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OrderShipName', models.CharField(max_length=100)),
                ('OrderShipAddress', models.CharField(max_length=100)),
                ('OrderShipAddress2', models.CharField(max_length=100)),
                ('OrderCity', models.CharField(max_length=50)),
                ('OrderState', models.CharField(max_length=50)),
                ('OrderZip', models.CharField(max_length=20)),
                ('OrderCountry', models.CharField(max_length=50)),
                ('OrderPhone', models.CharField(max_length=20)),
                ('OrderFax', models.CharField(max_length=20)),
                ('OrderShipping', models.DecimalField(decimal_places=4, max_digits=4)),
                ('OrderTax', models.DecimalField(decimal_places=4, max_digits=5)),
                ('OrderEmail', models.EmailField(max_length=100)),
                ('OrderDate', models.DateTimeField(auto_now=True)),
                ('OrderShipped', models.BooleanField(default=1)),
                ('OrderTrackingNumber', models.CharField(max_length=80)),
                ('OrderUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user')),
            ],
        ),
    ]
