# Generated by Django 3.2.2 on 2021-05-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(default='default_category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductSKU', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProductWeight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ProductCartDesc', models.CharField(max_length=250)),
                ('ProductShortDesc', models.CharField(max_length=1000)),
                ('ProductLongDesc', models.TextField()),
                ('ProductThumb', models.CharField(max_length=100)),
                ('ProductImage', models.URLField()),
                ('ProductUpdateDate', models.DateTimeField(auto_now=True)),
                ('ProductStock', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ProductLive', models.IntegerField(default=1)),
                ('ProductUnlimited', models.IntegerField(default=1)),
                ('ProductLocation', models.CharField(max_length=250)),
                ('ProductCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
