# Generated by Django 3.2.2 on 2021-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductLive',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductUnlimited',
            field=models.BooleanField(default=1),
        ),
    ]
