# Generated by Django 3.2.2 on 2021-05-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210510_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionID', models.IntegerField(max_length=11)),
                ('OptionGroundID', models.IntegerField(max_length=11)),
                ('OptionPriceIncrement', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product')),
            ],
        ),
    ]
